<section class="admin-hero">
    <div><h1>Kelola Jadwal Lapangan</h1><p>Tambah dan atur slot yang dapat dipesan customer.</p></div>
    <div class="admin-hero-actions"><a class="admin-secondary-btn" href="<?php echo e(app_url('admin/lapangan')); ?>"><i class="fa-solid fa-arrow-left"></i> Lapangan</a><button class="btn-primary" type="button" data-dialog-open="scheduleCreateDialog"><i class="fa-solid fa-plus"></i> Tambah Jadwal</button></div>
</section>

<div class="admin-content-section">
    <form class="admin-filter-bar" method="get" action="<?php echo e(app_url('admin/jadwal')); ?>">
        <select class="admin-filter-select" name="field" aria-label="Pilih lapangan" onchange="this.form.submit()"><option value="">Semua Lapangan</option><?php foreach ($scheduleFields as $field): ?><option value="<?php echo e($field['id']); ?>" <?php echo $selectedField === $field['id'] ? 'selected' : ''; ?>><?php echo e($field['name']); ?></option><?php endforeach; ?></select>
    </form>
    <article class="admin-panel admin-full-width"><div class="admin-table-responsive"><table class="admin-table"><thead><tr><th>Lapangan</th><th>Tanggal</th><th>Waktu</th><th>Harga</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
        <?php if (empty($schedules)): ?><tr><td colspan="6">Belum ada jadwal untuk pilihan ini.</td></tr><?php endif; ?>
        <?php foreach ($schedules as $schedule): ?><tr><td><?php echo e($schedule['Nama_lapangan']); ?></td><td><?php echo e($schedule['Tanggal']); ?></td><td><?php echo e(substr($schedule['Jam_Mulai'], 0, 5) . ' - ' . substr($schedule['Jam_Selesai'], 0, 5)); ?></td><td>Rp<?php echo e(number_format($schedule['Harga'], 0, ',', '.')); ?></td><td><span class="admin-badge <?php echo strtolower($schedule['Status']) === 'available' ? 'success' : 'warning'; ?>"><?php echo e($schedule['Status']); ?></span></td><td><div class="admin-actions"><button class="btn-icon" type="button" data-dialog-open="scheduleEditDialog" data-payload="<?php echo e(json_encode(array('id_jadwal' => $schedule['ID_Jadwal'], 'id_lapangan' => $schedule['ID_Lapangan'], 'tanggal' => $schedule['Tanggal'], 'jam_mulai' => substr($schedule['Jam_Mulai'], 0, 5), 'jam_selesai' => substr($schedule['Jam_Selesai'], 0, 5), 'harga' => $schedule['Harga'], 'status' => $schedule['Status']))); ?>"><i class="fa-solid fa-pen"></i></button><form class="admin-inline-form" action="<?php echo e(app_url('admin/jadwal/hapus')); ?>" method="post" data-confirm="Hapus slot jadwal ini?"><input type="hidden" name="admin_token" value="<?php echo e($adminToken); ?>"><input type="hidden" name="id_jadwal" value="<?php echo e($schedule['ID_Jadwal']); ?>"><input type="hidden" name="id_lapangan" value="<?php echo e($schedule['ID_Lapangan']); ?>"><button class="btn-icon danger" type="submit"><i class="fa-solid fa-trash"></i></button></form></div></td></tr><?php endforeach; ?>
    </tbody></table></div><div class="admin-pagination"><span>Menampilkan <?php echo e(count($schedules)); ?> jadwal</span></div></article>
</div>

<dialog class="admin-dialog" id="scheduleCreateDialog"><div class="admin-dialog-head"><h2>Tambah Jadwal</h2><button class="admin-dialog-close" type="button" data-dialog-close>&times;</button></div><form class="admin-dialog-form" action="<?php echo e(app_url('admin/jadwal/tambah')); ?>" method="post"><input type="hidden" name="admin_token" value="<?php echo e($adminToken); ?>"><label class="full"><span>Lapangan</span><select name="id_lapangan" required><?php foreach ($scheduleFields as $field): ?><option value="<?php echo e($field['id']); ?>" <?php echo $selectedField === $field['id'] ? 'selected' : ''; ?>><?php echo e($field['name']); ?></option><?php endforeach; ?></select></label><label><span>Tanggal</span><input type="date" name="tanggal" min="<?php echo e(date('Y-m-d')); ?>" required></label><label><span>Harga</span><input type="number" name="harga" min="0" required></label><label><span>Mulai</span><input type="time" name="jam_mulai" required></label><label><span>Selesai</span><input type="time" name="jam_selesai" required></label><div class="admin-dialog-actions"><button type="button" class="admin-secondary-btn" data-dialog-close>Batal</button><button type="submit" class="btn-primary">Tambah</button></div></form></dialog>

<dialog class="admin-dialog" id="scheduleEditDialog"><div class="admin-dialog-head"><h2>Edit Jadwal</h2><button class="admin-dialog-close" type="button" data-dialog-close>&times;</button></div><form class="admin-dialog-form" action="<?php echo e(app_url('admin/jadwal/update')); ?>" method="post"><input type="hidden" name="admin_token" value="<?php echo e($adminToken); ?>"><input type="hidden" name="id_jadwal"><label class="full"><span>Lapangan</span><select name="id_lapangan" required><?php foreach ($scheduleFields as $field): ?><option value="<?php echo e($field['id']); ?>"><?php echo e($field['name']); ?></option><?php endforeach; ?></select></label><label><span>Tanggal</span><input type="date" name="tanggal" required></label><label><span>Harga</span><input type="number" name="harga" min="0" required></label><label><span>Mulai</span><input type="time" name="jam_mulai" required></label><label><span>Selesai</span><input type="time" name="jam_selesai" required></label><label class="full"><span>Status</span><select name="status"><option>Available</option><option>Blocked</option><option>Maintenance</option></select></label><div class="admin-dialog-actions"><button type="button" class="admin-secondary-btn" data-dialog-close>Batal</button><button type="submit" class="btn-primary">Simpan</button></div></form></dialog>
